/* Generated by BuildNumber Version 0.8 */

#ifndef HAPBUILDNUMBER_HPP_ 
#define HAPBUILDNUMBER_HPP_ 

#define HOMEKIT_VERSION_BUILD 78
#define HOMEKIT_VERSION_BUILD_STR "78" 

#endif /* HAPBUILDNUMBER_HPP_ */
